# Generated by Django 2.2.4 on 2020-01-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
