# Generated by Django 3.0.2 on 2020-02-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='slug',
            field=models.SlugField(default='ZWxzHP', max_length=6, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='p9077Z', max_length=6, unique=True, verbose_name='slug'),
        ),
    ]
