# Generated by Django 3.0.2 on 2020-02-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200207_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='slug',
            field=models.SlugField(default='vlShaM', max_length=6, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='Zjpatp', max_length=6, unique=True, verbose_name='slug'),
        ),
    ]
