# Generated by Django 3.0.2 on 2020-01-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200131_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='xJXmUi', max_length=6, unique=True),
        ),
    ]
