# Generated by Django 3.0.2 on 2020-01-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200131_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='OgVqOL', max_length=6, unique=True, verbose_name='slug'),
        ),
    ]
