# Generated by Django 3.0.2 on 2020-01-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200201_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='slug',
            field=models.SlugField(default='Zc8Jgt', max_length=6, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='c6nv1c', max_length=6, unique=True, verbose_name='slug'),
        ),
    ]
