# Generated by Django 3.0.2 on 2020-01-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200201_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='slug',
            field=models.SlugField(default='RjrqTF', max_length=6, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='writer',
            field=models.CharField(default='parrotadmin', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='Z6c2I6', max_length=6, unique=True, verbose_name='slug'),
        ),
    ]
