# Generated by Django 3.0.2 on 2020-02-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200201_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_ranking', models.IntegerField(default=0)),
                ('submission_file', models.FileField(default=None, upload_to='documents/')),
                ('submission_status', models.CharField(max_length=50)),
                ('submission_time', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
            ],
            options={
                'verbose_name': 'submission',
                'verbose_name_plural': 'submissions',
                'db_table': 'parrot_con',
                'ordering': ('-user_ranking',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_ranking', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ('-modify_date',), 'verbose_name': 'notice', 'verbose_name_plural': 'notices'},
        ),
        migrations.AlterField(
            model_name='notice',
            name='slug',
            field=models.SlugField(default='9wZrLh', max_length=6, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='Uq2pqv', max_length=6, unique=True, verbose_name='slug'),
        ),
    ]
