# Generated by Django 3.0.2 on 2020-01-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200201_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='mMYEcP', max_length=6, unique=True, verbose_name='slug'),
        ),
    ]
